version: 1
services:
  - type: web
    name: my-fastapi-app
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn -w 4 -b 0.0.0.0:8000 App:app"
    envVars:
      - key: MY_ENV_VAR
        value: "value_here"